# Frontend Dockerfile
FROM node:18-alpine AS build

WORKDIR /app

# copy package files and install dependencies
COPY package*.json ./
RUN npm install

# copy all source files
COPY . .

# Build the React app
RUN npm run build

# Serve with nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80

# Run Nginx in foreground
CMD ["nginx", "-g", "daemon off;"]